### ISSUE TITLE
Quick Reply not working

### ISSUE THREAD

**Issue by Kaijiro** [Microsoft/botbuilder-python#100]
Hey,

I'm using botbuilder version 4.0.0a6 and I have a struggle with quick replies.
Quick replies are displayed in the emulator but not in any other Skype Client.

Here is the code I used : 
```python
def handle_request(self, request, channel_model):
    data = request.data

    activity = Activity.deserialize(data)

    if not self.__handle_authentication__(request, channel_model):
        return

    if activity.type == ActivityTypes.message.value:
        resp_activity = Activity(
            type=ActivityTypes.message,
            channel_id=activity.channel_id,
            conversation=activity.conversation,
            from_property=activity.recipient,
            recipient=activity.from_property,
            service_url=activity.service_url
        )

        replies = [
            {
                "title": "Test1",
                "type": ActionTypes.im_back,
                "value": "Test1",
            },
            {
                "title": "Test2",
                "type": ActionTypes.im_back,
                "value": "Test2",
            }
        ]

        resp_activity.text = "My text"
        resp_activity.suggested_actions = SuggestedActions(actions=replies, to=[activity.from_property.id])

        credentials = MicrosoftAppCredentials(channel_model.settings["app_id"], channel_model.settings["app_password"])

        try:
            connector = ConnectorClient(credentials, response_activity.service_url)
            connector.conversations.send_to_conversation(resp_activity.conversation.id, response_activity)
        except Exception as e:
            print("An error happened ! ")
            traceback.print_tb(e.__traceback__)
    else:
        return
```

Any help is really appreciated

**Comment by stevengum** [comment]
Hey @Kajiro, 
This is due to a channel limitation on Skype's end. They unfortunately do not support SuggestedActions aka "Quick Replies" if they are not part of a Card. 

([See Channel Skype: | Feature: Suggested actions, then Notes -> Availability](https://docs.botframework.com/en-us/channel-inspector/channels/Skype/))

I spun up a v3 Node.js bot to test as well, and Skype did not send the activity's text in addition to the suggestedActions.

**Comment by stevengum** [comment]
I checked my bot again and saw that it was possible using version 12.1815.210.0 on Windows 10 Enterprise, so I'm looking back into this, sorry @Kaijiro!

**Comment by Kaijiro** [comment]
No problem, thank you for the investigation. If you need me to test anything, feel free to ask !

**Comment by stevengum** [comment]
@Kaijiro, the issue was actually that the suggestedAction was being sent to the bot instead of to the user. The correct code is this:

```py
activity.suggested_actions = SuggestedActions(actions=replies, to=[activity.recipient.id])
```

as opposed to this:

```py
activity.suggested_actions = SuggestedActions(actions=replies, to=[activity.from_property.id])
```

For some reason the Emulator was rendering the SuggestedActions to you, when in reality you shouldn't have been seeing them at all.

I opened a bug on Microsoft/BotFramework-WebChat#1057 to fix this bug in webchat (which is used in the Emulator).

Let me know if this solves the problem for you

**Comment by Kaijiro** [comment]
Are you sure about this ? Here, my `activity` variable is the result of the request deserialization, so the `from` attribute of `activity` is my final user and the `recipient` is the bot itself.

Please, correct me if I'm wrong.

**Comment by stevengum** [comment]
@Kaijiro sorry I missed your earlier comment; the code you've changed it to above should be correct; developers should be using the incoming deserialized `activity` to generate the `SuggestedActions.to` property on the response activity by using  `activity.from_property`

**Comment by Kaijiro** [comment]
Hey !
I changed the code because I had a copy/paste error. This is the code actually used to send SuggestedActions but I can only see it in the Emulator, every other client does not render it.

**Comment by stevengum** [comment]
It sounds like you've been squared away for some time, so I'm going to close this out for now. If you're still facing this problem, please create a new issue.
