### ISSUE TITLE
[PORT] Add OnContinueConversation trigger and ContinueConversationLater action

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#1164]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/4063

* Add **PostActivityAsync** method to **BotFrameworkHttpClient** to make it easy to post secure EventActivity to your bot
* Add **OnContinueConversation** trigger
* Add **ContinueConversationLater** action to BotBuilder.Azure
* Add unit tests, etc.

# Changed projects
* Microsoft.Bot.Builder.Azure
* Microsoft.Bot.Builder.Dialogs.Adaptive
* integration
* Microsoft.Bot.Builder.Azure.Tests
* Microsoft.Bot.Builder.Tests

**Comment by denscollo** [comment]
We reviewed the issue and found that in BotBuilder-Dotnet the changes in Azure.Queues library were then refactored in the [PR#4692](https://github.com/microsoft/botbuilder-dotnet/pull/4692) moving ContinueConversationLater class to Dialogs.Adaptive.
This port can't be done because BotBuilder-Python doesn't contain either the Azure.Queues nor Dialogs.Adaptive libraries. To port this change these libraries should be ported first.
