### ISSUE TITLE
I've done bot typing in python, which works on Emulator but not on the server. What's the problem?

### ISSUE THREAD

**Issue by sujeongHeo** [Microsoft/botbuilder-python#147]
## Version
Python 3.6

## Describe the bug

I've done bot typing in python, 
which works Emulator 
 but not  works on the server. What's the problem?

## To Reproduce

It works on Emulator,  but When I deploy to HEROKU server, It doesn't work.

## Screenshots
![image](https://user-images.githubusercontent.com/41574104/56706397-bfd51180-674f-11e9-84c8-75fc4bba1a32.png)
This screenshot is works on Emulator. you can see the '...'  .

![image (1)](https://user-images.githubusercontent.com/41574104/56706407-d11e1e00-674f-11e9-84a0-9310dff51b4e.png)

But this is on our server. We can't see the '...' 

[bug]

It works on local, Python Emulator  But doesn't work on Heroku server. Thank you.

**Comment by tdurnford** [comment]
The Microsoft Bot Framework team prefers that **how to** questions be submitted on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework). The official [Bot Framework Github](https://github.com/Microsoft/BotBuilder/blob/master/README.md) repos are the preferred platform for submitting **bug fixes** and **feature requests**.

Since your question is more of a how to rather than a bug and you've already asked a [question](https://stackoverflow.com/questions/55840837/ive-done-bot-typing-in-python-which-works-locally-but-not-on-the-server-what) on StackOverflow, we'll be sure to help you resolve your issue there. I would recommend adding code snippets to your question. regarding how you are sending the activities. This issue is most likely related to the behavioral differences between channels and needing to add a `time.sleep(seconds)` between sending activities since you are using BotChat/iFrame.

```python
import time

...

await turn_context.send_activity(Activity(type=ActivityTypes.typing))
time.sleep(3)  # wait before sending the next activity
await turn_context.send_activity("Hello world")
```
