### ISSUE TITLE
Some fixes have not been correctly released on pip

### ISSUE THREAD

**Issue by ThibaultDieudonne** [microsoft/botbuilder-python#1938]
After installing botbuilder-core last release from pip, I had the exact error described and fixed in the issue #1880. It appears that the telemetry_logger_middleware.py file hasn't been updated in pip.
It can easily be checked by installing botbuilder-core with pip, then in botbuilder/core/telemetry_logger_middleware.py L220 should be "if activity.attachments and len(activity.attachments) > 0:" instead of "if activity.attachments and activity.attachments.strip():".
Would appreciate if you could update the pip repository.

**Comment by anishprasad01** [comment]
Hi @ThibaultDieudonne,

It's not that it hasn't been updated correctly, but rather that it hasn't been released yet. PR #1888 containing the fix was merged into main on January 28th, 2022, but the last release of the Python SDK, [4.14.1](https://github.com/microsoft/botbuilder-python/releases/tag/4.14.1), was published on January 4th, 2022.

Until such a time as a new Python SDK version is released, you can clone the fix from main and use it in your bot.
