### ISSUE TITLE
botbuilder-dialogs {legacy-install-failure}

### ISSUE THREAD

**Issue by SahuSomesh** [microsoft/botbuilder-python#1943]
## Version
What package version of the SDK are you using.
Bot-builder-Samples/multi-turn-prompt

## Describe the bug
Give a clear and concise description of what the bug is.
I was installing botbuilder-dialog using "pip install botbuilder-dialog==4.14.0 or 4.14.2".
but i am unable to install this module, as I encountered this error
"legacy-install-failure"

## Expected behavior
Give a clear and concise description of what you expected to happen.
I am expecting the module to be installed, so that i can able to run the multi-turn-prompt bot

## Screenshots
![image](https://user-images.githubusercontent.com/75417647/170436558-e26b8c5b-ecfe-4c59-9b94-6471ae016f3c.png)

**Comment by stevkan** [comment]
> pip install botbuilder-dialog==4.14.0 or 4.14.2

@SahuSomesh, can you verify for me if this is the command you actually used? I only ask as the package you have in the command should be `botbuilder-dialogs` (with an 's'), instead of `botbuilder-dialog`.

Also, I'm not sure if you are intending the 'or' in the install command to work or if that is just informational. But, if you are intending to have two versions installed, please read this Stack Overflow [post](https://stackoverflow.com/a/6572017/3962636) for clarification on how you could achieve this. The statement you have above will not work, as-is.

**Comment by SahuSomesh** [comment]
> > pip install botbuilder-dialog==4.14.0 or 4.14.2
> 
> @SahuSomesh, can you verify for me if this is the command you actually used? I only ask as the package you have in the command should be `botbuilder-dialogs` (with an 's'), instead of `botbuilder-dialog`.
> 
> Also, I'm not sure if you are intending the 'or' in the install command to work or if that is just informational. But, if you are intending to have two versions installed, please read this Stack Overflow [post](https://stackoverflow.com/a/6572017/3962636) for clarification on how you could achieve this. The statement you have above will not work, as-is.

Hey @stevkan I used this command 
"pip install botbuilder-dialogs==4.14.0" this is not working so I have used this command
"pip install botbuilder-dialogs==4.14.2" this is also not working.
I have also tried to use this command "pip install botbuilder-dialogs" but i am unable to install the module.

and yeah that 'or' in the install command is just for informational purpose.

**Comment by stevkan** [comment]
@SahuSomesh - Unfortunately, I am unable to repro the issue. I can install both versions of the botbuilder-dialogs library without issue. Looking at the attached image of the error you are receiving, it mentions a 'legacy-install-failure' to which I see this when I install:

```
Using legacy 'setup.py install' for aiounittest, since package 'wheel' is not installed.
Using legacy 'setup.py install' for regex, since package 'wheel' is not installed.
Using legacy 'setup.py install' for emoji, since package 'wheel' is not installed.
Using legacy 'setup.py install' for grapheme, since package 'wheel' is not installed.
```

I am using version Python version 3.10.2 and looking in Python's install folder in 'Project Files', I can find the 'setup.py' script located in a couple different folders (I'm not sure which is referenced). Perhaps verify that you have these files installed?

![image](https://user-images.githubusercontent.com/18403946/171476506-ba80311b-bd9f-4cdf-a96e-23ef6dc94cf7.png)

You can also double check that the environment settings are setup correctly for Python so that all commands are available. I have the following in my system environment path (Windows system).

```
C:\Program Files\Python310\Scripts\
C:\Program Files\Python310\
```

Lastly, I also noticed in the attached image that your version of 'pip' is outdated. You may want to try updating that, in case that is a factor. That being said, I currently have pip version 21.2.4.

**Comment by SahuSomesh** [comment]
Hey @stevkan Thanks for updating,
i will try to update pip and also try to install the wheel package.

Thanks :)
