### ISSUE TITLE
Update deployment template

### ISSUE THREAD

**Issue by woasishen** [microsoft/botbuilder-python#1945]
I'm from azure bot service team,
Azure bot service have split the deployment of AppService and AzureBot.
So, we want to change the templates.
Also, we will publish AzureBot regionality soon.
So, we add a configuration about AzureBotRegion.

**Comment by alankashkash** [comment]
Hey, for the last 5 days I've been facing issues with deployment. Can it be caused by the deployment template?
My errors are either https://github.com/Azure/azure-functions-python-worker/issues/713 or 022-06-29T08:39:23.765016298Z Traceback (most recent call last):2022-06-29T08:39:23.765019898Z File "/tmp/8da59a981c9be43/antenv/lib/python3.7/site-packages/botbuilder/core/integration/aiohttp_channel_service_exception_middleware.py", line 20, in aiohttp_error_middleware2022-06-29T08:39:23.765023698Z response = await handler(request)2022-06-29T08:39:23.765027198Z File "/tmp/8da59a981c9be43/antenv/lib/python3.7/site-packages/aiohttp/web_urldispatcher.py", line 927, in _handle2022-06-29T08:39:23.765030998Z raise self._http_exception2022-06-29T08:39:23.765034498Z aiohttp.web_exceptions.HTTPNotFound: Not Found
