### ISSUE TITLE
Getting error while building wheel file for regex while installing botbuilder-dialog library

### ISSUE THREAD

**Issue by MamtaKumari24** [microsoft/botbuilder-python#1949]
### Use this [query](https://github.com/Microsoft/botbuilder-python/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MamtaKumari24** [comment]
botbuilder-dialog for python 3.9 depends on regex version <=2019.08.19 and these regex versions are not compatible with python 3.9. Code throwing an error while building wheel file for regex.

**Comment by anishprasad01** [comment]
@MamtaKumari24,

Thank you for the report, I am Invetigating.

**Comment by anishprasad01** [comment]
At the moment, we [support the use of Python 3.7 or 3.8](https://learn.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=python%2Cvs#prerequisites) for Bot Framework bots built with the Python SDK. I have verified that Python bots correctly build and run on the supported version.

We will keep your feature request in mind, but please note that due to the forthcoming retirement and end of support for the Python SDK in November 2023, it is unlikely that newer Python versions will be supported.

**Comment by libcthorne** [comment]
> At the moment, we [support the use of Python 3.7 or 3.8](https://learn.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=python%2Cvs#prerequisites) for Bot Framework bots built with the Python SDK. I have verified that Python bots correctly build and run on the supported version.
> 
> We will keep your feature request in mind, but please note that due to the forthcoming retirement and end of support for the Python SDK in November 2023, it is unlikely that newer Python versions will be supported.

Is this end of support still planned?
