### ISSUE TITLE
TeamsInfo.get_member() errors out for a skill bot

### ISSUE THREAD

**Issue by yashna-shravani** [microsoft/botbuilder-python#1981]
## Version
4.14

## Describe the bug
Using Python SDK bot as skill bot and calling TeamsInfo.get_member() function to get user name and email. This gives me error= _Operation returned an invalid status code 'Method Not Allowed'_ .  But as a root bot it works fine. Why does it errors out as a skill bot?

## Expected behavior
To return Teams user details

**Comment by anishprasad01** [comment]
Hi @yashna-shravani,

Have you double-checked and verified that your skill manifests are correct and that your skill bot has the appropriate access permissions? As long as you have a valid setup are passing in valid parameters, it should work with skill bots.

**Comment by yashna-shravani** [comment]
Hi @anishprasad01 
Could you share any sample skill manifest with valid permission? Just saw in some older git issues that TeamsInfo does not work in any skill bot.

**Comment by anishprasad01** [comment]
@yashna-shravani,

My mistake, you're correct. This was a known issue with skill bots. The issue was identified and fixed for the C# and Javascript SDKs earlier this year. However, since the [Python](https://github.com/Microsoft/botbuilder-python#:~:text=The%20Bot%20Framework,Virtual%20Agents.) and [Java](https://github.com/Microsoft/botbuilder-java#:~:text=The%20Bot%20Framework,Virtual%20Agents.) Bot Framework SDKs are being retired, only critical bug and security fixes are being undertaken. Given this, it is unlikely that this fix will be ported to Python or Java. 

Additionally, the `TeamsInfo.get_members` endpoint is itself being [deprecated](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/team-chat-member-api-changes), and you will need to move to the new paginated endpoints or make use of one of the other options mentioned in the linked deprecation document. These newer endpoints may serve as an appropriate workaround for this issue.
