### ISSUE TITLE
date_resolver_dialog - test of "definite"

### ISSUE THREAD

**Issue by ochotin** [microsoft/botbuilder-python#292]
## Version SDK v4.5.0b3
in botbuilder-python/samples/13.core-bot/dialogs/date_resolver_dialog.py

## Describe the bug
Line : _if "definite" in Timex(timex).types:_
The goal of this line is to treat ambiguous date such as timex date = XXXX-05-17
so the test must be "not in" instead of "in" ("definite" = type for an unambiguous date)

[bug]

**Comment by Zerryth** [comment]
Hmm, it looks like the behavior in the Python version of CoreBot is different from the behavior of what happens in C# and JS versions.

I'll need to investigate further on why the discrepancy occurs though
___
For the line that you pointed out in question, for it the bot actually ventures down the if statement checking for for definite inside date resolver dialog if you:
* start the dialog with an ambiguous date
* answer with the "to" and "from" locations in the next prompts asking for flight cities
* it should then detect that the initial date was given in the first utterance, and that that utterance is ambiguous, and send that "reprompt" given in date resolver dialog

### Example of Behavior in JS/C#
![image](https://user-images.githubusercontent.com/35248895/62894201-254e0d80-bd01-11e9-9843-5c531aafd027.png)

### Example of Behavior in Python
![image](https://user-images.githubusercontent.com/35248895/62894299-52022500-bd01-11e9-933f-543861a55777.png)
Notice above it doesn't seem to detect that a date was initially given, nor does it reprompt, _even when changing the if statement you pointed out to use `not in`_
I tried changing where the `not` was placed "just in case" it made a different, but it doesn't.
![image](https://user-images.githubusercontent.com/35248895/62894498-a3aaaf80-bd01-11e9-8625-9ee499695ec0.png)

Running in debugger mode, I myself can't seem to get it to hit that if statement--seems to end that dialog before it would even reach it maybe?

Investigating further...

**Comment by Zerryth** [comment]
Ah ok, looks like it never hits LN 59 `if "definite" not in Timex(timex).types` in `date_resolver_dialog.py`, because the `step_context.options` is `None`, and therefore always will hit LN 52 `if timex is None` prompt  and never gets to LN 59.

I'll dig to see why this is, so we can finally hit LN 59 and ensure the changes produce the behavior expected

**Comment by Zerryth** [comment]
Ok, dug down and figured out why the sample bot is breaking on entities.

`MainDialog` calls `LuisHelper.execute_luis_query` to get `intent` and `result`

* If you take a look at `luis_helper.py`, you can see that the `execute_luis_query` method does indeed return `intent` & `result`. 
* Separately, we have the raw LUIS result that came from calling LUIS endpoint to predict intent, saved in `recognizer_result`. 
* The issue is **we never save any of the parsed entity values from `recognizer_result` to `result` that get returned, so therefore all the values in `result` that `MainDialog` has are `None`

Fixing the above issue first, then can actually hit the `if "definite" not in Timex(timex).type` statement originally reported.
