### ISSUE TITLE
echo bot deploy on azure

### ISSUE THREAD

**Issue by sherlock666** [microsoft/botbuilder-python#379]
Thanks for release echo bot  sample

However  How do I deploy it on azure?
(Perfectly run on BotFramework Emulator)
Is there any operation guide? 
We've need to use it to deploy LineBot for further Project by python

Thanks!!!

**Comment by anusharavindrar** [comment]
Hello,

You can refer to the following [comment](https://github.com/Microsoft/botbuilder-python/issues/101#issuecomment-456222233) on a similar Python bot deployment issue which provides the steps to deploy your Python bot on Azure.

Hope this helps. Please try this and let me know if you have any issues.

**Comment by sherlock666** [comment]
Thanks for reply
Actually I've try that completely follow the operation. (Use App Service. And for test the echo.  I link it to bot channel service)
But get failure result at last

Also seems some interface had been change 
Maybe need some update?

**Comment by sherlock666** [comment]
Are you getting an error while you 'Test in Web Chat'?

Yes!!  I got no error from his guide
Until his last part. Test in web chat
Because no description
So I just connect them. 
Not really sure how to do?

Possible for publish more detail guide?

Thanks!!

**Comment by anusharavindrar** [comment]
The detailed steps for the last part:

- Click on the 'All App service settings' blade on the left side under the App Service Settings section for your bot.
![az2](https://user-images.githubusercontent.com/48731427/67884698-81a41a80-fb03-11e9-8014-3d8ce00f83ef.png)


- This will open up your app's Overview page which has the basic management tasks like browse, stop, start, restart, and delete. Click on 'Restart' to restart your App Service. Once you click, you will get a pop-up asking if you are sure you want to restart the app, click on 'Yes'(Note: It might take a few minutes for the changes to be propagated).
![az3](https://user-images.githubusercontent.com/48731427/67884307-d5faca80-fb02-11e9-916b-58f4e9d962c7.png)

- Then, you can navigate to your Web App Bot and click on the 'Test in Web Chat' blade under Bot management.
![az4](https://user-images.githubusercontent.com/48731427/67884589-51f51280-fb03-11e9-9812-e04ab2d60cdb.png)

- Send a message to your Python bot.
![az5](https://user-images.githubusercontent.com/48731427/67885074-2de60100-fb04-11e9-8c7d-d49e1d06529a.png)


Hope this helps.

**Comment by sherlock666** [comment]
Thanks ~
And how about App_Id and App_Password?
The guide didn't say where to get them

**Comment by anusharavindrar** [comment]
As per the guide, "You will need to create a new app in the Application Registration Portal and generate a new password. Keep track of the **Application Id and Password** as you need them in the command below to create the bot registration and later on when we configure the environment variables." 
 
Since the Application Registration Portal has been deprecated, you will need to make use of the '**App Registrations**' on Azure.

- Click on the '**Azure Active Directory**' on the left blade under Favorites. This will open up the Overview page for the directory.
![azure1](https://user-images.githubusercontent.com/48731427/67966077-6f3be680-fbc0-11e9-8922-e8d742b33cda.png)


- Click on the '**App registrations**' under Manage section on the left blade. This page will display all the applications with the options of creating a new registration on the top panel. 
![azure2](https://user-images.githubusercontent.com/48731427/67966178-a4483900-fbc0-11e9-868b-667b60186e35.png)


- Click on the **+ New Registration** option. This will open up the registration page where you would fill in the name of the application, choose the account type(depending on your requirement) and then click on 'Register'. This will create the new app and display the overview page with the application ID, directory ID, display name etc. Copy the **Application ID** and save it on a notepad or any quick access tool for the next step.

![azure3](https://user-images.githubusercontent.com/48731427/67966283-dbb6e580-fbc0-11e9-9f60-ef971a5d2e58.png)


![azure4](https://user-images.githubusercontent.com/48731427/67968381-811f8880-fbc4-11e9-9d6d-7da6ded4eaf8.png)


![azure5](https://user-images.githubusercontent.com/48731427/67966951-06556e00-fbc2-11e9-9a81-261ce78e3077.png)


- Now click on the '**Certificates & secrets**' under the Manage section on the left blade. It will open up the overview page for certificates and client secret. Click on the '**+ New client secret**' option under Client secrets.
![azure6](https://user-images.githubusercontent.com/48731427/67967229-7bc13e80-fbc2-11e9-8ede-18b879811bd1.png)

- This will open a pop-up which will ask you for a description and select '**Never**' option for Expires and click on 'Add'.
![azure7](https://user-images.githubusercontent.com/48731427/67967417-ce9af600-fbc2-11e9-9aa8-546dad5f6758.png)

- Copy the value of the appSecret(**Application Password**) and save it some place secure as this is the only time you can view the value. **If you lose the client secret, then you will have to create a new client secret.** 
![azure8](https://user-images.githubusercontent.com/48731427/67967628-32bdba00-fbc3-11e9-8afc-6cb1659376e0.png)

This **Application Id** and **Password** will be needed in the '**az bot create**' command  to create a new bot registration and later on when we configure the environment variables.

Hope this helps.

**Comment by sherlock666** [comment]
Great Thanks for support
Finally Successfully deploy

Will continue on LineBot development on azure webapp
I recommend the document here may merge with the guide

(Let's keep in contact on MS internal Team  Thanks!!!)

**Comment by sherlock666** [comment]
Is it possible to make an example
for Azure Bot Service or Azure Bot Channel
about Linebot(python version) Deployment sample?
Currently there's no sample for a merging version for Linebot(python version) with azure service

People usually use Line(something like WeChat) in Asia 
I have a LineBot on Heroku Server now
But I hope to move it to Azure  However not sure how to change setting in my code

Thank!!

https://developers.line.biz/en/docs/messaging-api/line-bot-sdk/

**Comment by anusharavindrar** [comment]
Glad that you were able to successfully deploy your bot on Azure. I have put across your recommendation about having a Linebot deployment sample to the botbuilder-python team. Closing the issue as its resolved.
