### ISSUE TITLE
Move Wiki to Docs?

### ISSUE THREAD

**Issue by szul** [Microsoft/botbuilder-python#40]
Any chance the wiki information (like for building) gets moved to the repo so that others can edit/contribute? The current build/installation guide has some ambiguities when it comes to the virtual environment stuff. I've made a more explicit instruction set in a [sample repo](https://github.com/szul/py-bot/blob/master/README.md) I'm building out, but would like to document items as I move along, and contribute back, if it's appropriate.

**Comment by stevengum97** [comment]
That's a good idea, but right now we (bb-py) are on a pause while we flesh some things out on the dotnet and js repos. @johnataylor might have a better idea of how to proceed regarding the documentation, as currently the [docs stub](https://github.com/Microsoft/botbuilder-python/tree/master/doc) is barren. 

Another thing worth mentioning is that it looks like the docs themselves are in flux across js and dotnet; js is shaping up to be a reference for the packages and its contents will probably go towads something like [this](https://docs.botframework.com/en-us/node/builder/chat-reference/index.html). Meanwhile, dotnet has an [overview.md](https://github.com/Microsoft/botbuilder-dotnet/blob/ae91885f95d14d9059de224a58f50b16042c477d/doc/overview.md) and that's it.

All of that said, I think it would be fantastic if you could specify some of the issues you've had with the wiki and someone will be able to fix the wiki as needed.

**Comment by szul** [comment]
The wiki is a bit ambiguous as to which should be done in a virtual environment and which shouldn’t between the virtual linking, the wheel building, the global installs/updates, and the installation of the bot builder into an actual bot project versus building locally. It’s a quick start guide, but I feel it would benefit from fleshing out specific paths for building/installing/using... but if developed is paused until the other SDKs are fleshed out, then I guess it’s a moot point for now.

**Comment by stevengum97** [comment]
@szul, I think I follow along what you're saying without even having to take a look at the docs today... As is probably obvious, the wiki was written before the packages were published, which is why they use things like `pip install -e .` as opposed to doing a simple `pip install botbuilder-core`.

Am I correct in saying that the root cause of the confusion might be due to a jumbling together of concepts like setting up the packages like someone forked the repo (building locally), as opposed to what you mention of installing the botbuilder packages into an actual project?

Regarding your last sentence I think we can still get something out to clear up these ambiguities, I'll talk to one of our docs team to see if they can do a cleanup. 😃

**Comment by szul** [comment]
Building locally is fine since the SDK is in flux as a prelease, but combining that local build with a project, while trying to keep that local project in a virtual environment is where it gets tricky, especially since there’s the `-e` instructions and the wheel instructions on the same page, but without that clear of a separation between the two paths that can be taken for installation.

I have no problem waiting for the official docs, and then seeing where I can help out. I’m going to take an older example bot I did for a conference that had a bunch of test controls, and try to convert it—so I should have some feedback then. 

Thanks for looking into this, and letting me know the status.
