### ISSUE TITLE
[PORT] Proactive auth: trust incoming token url conditionally

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-python#852]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3532

# Changed projects
* Microsoft.Bot.Builder

**Comment by EricDahlvang** [comment]
This is not an issue with the Python sdk due to MicrosoftAppCredentials allowing for an empty password: https://github.com/microsoft/botbuilder-python/blob/master/libraries/botframework-connector/botframework/connector/auth/microsoft_app_credentials.py#L77

```python
    def _should_authorize(self, session: requests.Session) -> bool:
        """
        Override of AppCredentials._should_authorize
        :param session:
        :return:
        """
        return self.microsoft_app_id and self.microsoft_app_password
```


However, it would be good to investigate if `signed_session`, or consumers, should call `_is_trusted_url`

```python
def signed_session(self, session: requests.Session = None) -> requests.Session:
        """
        Gets the signed session.  This is called by the msrest package
        :returns: Signed requests.Session object
        """
        if not session:
            session = requests.Session()

        if not self._should_authorize(session):
            session.headers.pop("Authorization", None)
        else:
            auth_token = self.get_access_token()
            header = "{} {}".format("Bearer", auth_token)
            session.headers["Authorization"] = header

        return session
```
https://github.com/microsoft/botbuilder-python/blob/master/libraries/botframework-connector/botframework/connector/auth/app_credentials.py#L95
