### ISSUE TITLE
Connecting the python code to microsoft teams bot

### ISSUE THREAD

**Issue by aniztar** [Microsoft/botbuilder-python#95]
Hello,

I am using this python code - https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-quickstart?view=azure-bot-service-4.0 to make a basic bot. It uses the botbuilder libraries. 
I have created a bot on microsoft teams. I got the app id and app password. I have used it in the above python code. Do I need to do anything else to connect this python code to the MS Teams bot? 

Thanks!

**Comment by stevengum** [comment]
@aniztar, no that should just about cover it. I'm going to close this issue as it's a "How-to" question and therefore belongs on Stack Overflow (where you already posted it, so thanks!). You're also already getting a lot of support from the community there, which is why we recommend "How-to" questions to be posted there! 

 For actual bugs, feature requests or enhancements with the SDK please feel free to file them here.

Cross linking [Stack Overflow question](https://stackoverflow.com/questions/51261623/connecting-the-python-code-to-microsoft-teams-bot).
